// server/utils/mailer.js
import nodemailer from "nodemailer";

/**
 * Sends the final HTML report to the user.
 * @param {string} userEmail - The email address of the user who started the test.
 * @param {Array} results - The array of result objects from the email checks.
 */
export const sendReportMail = async (userEmail, results) => {
  if (!Array.isArray(results)) {
    console.error("Mailer Error: The 'results' parameter is not an array.", results);
    return;
  }

  // --- ✅ Gmail SMTP Configuration ---
  const transporter = nodemailer.createTransport({
    service: "gmail", // Simplifies setup for Gmail
    auth: {
      user: process.env.REPORT_SENDER_EMAIL, // Your Gmail address
      pass: process.env.REPORT_SENDER_PASS,  // App password (not your login password!)
    },
  });

  const htmlReport = `
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; padding: 20px;">
      <h1 style="color: #0d6efd; text-align: center;">Email Deliverability Report</h1>
      <p>Here are the results for your recent test. All 5 inboxes were checked successfully.</p>
      <table style="border-collapse: collapse; width: 100%; margin-top: 20px;">
        <thead style="background-color: #f8f9fa;">
          <tr>
            <th style="padding: 12px; border: 1px solid #dee2e6;">Provider</th>
            <th style="padding: 12px; border: 1px solid #dee2e6;">Email</th>
            <th style="padding: 12px; border: 1px solid #dee2e6;">Status</th>
            <th style="padding: 12px; border: 1px solid #dee2e6;">Landed In</th>
          </tr>
        </thead>
        <tbody>
          ${results.map(r => `
            <tr>
              <td style="padding: 12px; border: 1px solid #dee2e6;">${r.provider || 'N/A'}</td>
              <td style="padding: 12px; border: 1px solid #dee2e6;">${r.email || 'N/A'}</td>
              <td style="padding: 12px; border: 1px solid #dee2e6;">
                <span style="background-color: ${r.status === 'Received' ? '#d1e7dd' : '#f8d7da'}; color: ${r.status === 'Received' ? '#0f5132' : '#842029'}; padding: 5px 10px; border-radius: 5px;">
                  ${r.status || 'N/A'}
                </span>
              </td>
              <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold; color: ${r.folder === 'Inbox' ? '#198754' : '#dc3545'};">
                ${r.folder || 'N/A'}
              </td>
            </tr>
          `).join("")}
        </tbody>
      </table>
      <p style="margin-top: 25px; font-size: 12px; color: #6c757d; text-align: center;">Report generated by Spam Report Tool.</p>
    </div>
  `;

  try {
    await transporter.sendMail({
      from: `"Spam Report Tool" <${process.env.REPORT_SENDER_EMAIL}>`,
      to: userEmail,
      subject: "Your Email Deliverability Report is Ready!",
      html: htmlReport,
    });
    console.log(`✅ Report email sent successfully to ${userEmail}`);
  } catch (error) {
    console.error("❌ Failed to send report email:", error);
  }
};
